name: Deploy 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SSH_USER: nuit_info
  SSH_KEY: ${{ secrets.SSH_KEY }}
  SSH_HOST: edgar.bzh

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/staging.key
        chmod 600 ~/.ssh/staging.key
        cat >>~/.ssh/config <<END
        Host staging
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/staging.key
          StrictHostKeyChecking no
        END
    - name: Check out the source
      run: scp -r main.py staging:/srv/nuit-info/
